### ISSUE TITLE
Node froze running idle

### ISSUE THREAD

**Issue by chrisvdg** [threefoldtech/0-core#38]
When running all bancadati nodes over the weekend, I found one node (`MAN-DC01-F0321-ARC06`) that was frozen and didn't respond to anything anymore, I couldn't go to the logs using `alt+f1` nor reset it using `ctrl+alt+del`.
Had to reset it using IPMI.

Frozen screen:
![image](https://user-images.githubusercontent.com/23582741/45287524-c4aec300-b4e8-11e8-885f-83306647d12d.png)

**Comment by muhamadazmy** [comment]
@chrisvdg there were no sign of activity on the console screen ? like Internet connectivity check or uptime change ?

**Comment by chrisvdg** [comment]
Nothing changed in the 5 minutes I was staring at it, before I send the ipmi command to power cycle the node.
Zt said the node was offline for 16 hours which corresponds roughly with the uptime on the console screen

**Comment by muhamadazmy** [comment]
Update:
We tried to check the crash report, and unfortunately it was empty.
Note:
I don't get why we have `debug + support + development` at the same time. Debug only control the log level in logs. And u definitely won't need `support` if u already set `development`

**Comment by chrisvdg** [comment]
Found an exception the logs, but no idea if related

```
2018-09-09T16:49:39.756Z: pm D >  Recurring '(monitor.cpu# monitor)' in 30s
2018-09-09T16:49:43.416Z: logger D >  [1]zrobot 2|Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/node_capacity/node_capacity.py", line 38, in _total
    self._node_sal.capacity.register()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/capacity/Capacity.py", line 111, in register
    _, resp = client.api.RegisterCapacity(data)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/api_service.py", line 167, in RegisterCapacity
    resp = self.client.post(uri, data, headers, query_params, content_type)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 62, in post
    return self._handle_data(uri, data, headers, params, content_type, self.session.post)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 58, in _handle_data
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://capacity.threefoldtoken.com/api/nodes
2018-09-09T16:49:43Z <Greenlet "Greenlet-0" at 0x7f8e20e0b648: _total(<node_capacity.NodeCapacity object at 0x7f8e238aa4)> failed with HTTPError

[Sun09 16:49] - base.py           :214 :service-ee7e0c18-b509-4628-9b7b-8cf8aff5db9b - ERROR    - error executing action _total:
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/template/decorator.py", line 66, in f_timeout
    return gl.get(block=True, timeout=seconds)
  File "src/gevent/greenlet.py", line 659, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.5/dist-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/node_capacity/node_capacity.py", line 38, in _total
    self._node_sal.capacity.register()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/capacity/Capacity.py", line 111, in register
    _, resp = client.api.RegisterCapacity(data)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/api_service.py", line 167, in RegisterCapacity
    resp = self.client.post(uri, data, headers, query_params, content_type)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 62, in post
    return self._handle_data(uri, data, headers, params, content_type, self.session.post)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 58, in _handle_data
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://capacity.threefoldtoken.com/api/nodes

ERROR:service-ee7e0c18-b509-4628-9b7b-8cf8aff5db9b:error executing action _total:
Traceback (most recent call last):
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/task/task.py", line 78, in execute
    self._result = self._func()
  File "/opt/code/github/threefoldtech/0-robot/zerorobot/template/decorator.py", line 66, in f_timeout
    return gl.get(block=True, timeout=seconds)
  File "src/gevent/greenlet.py", line 659, in gevent._greenlet.Greenlet.get
  File "src/gevent/greenlet.py", line 312, in gevent._greenlet.Greenlet._raise_exception
  File "/usr/local/lib/python3.5/dist-packages/gevent/_compat.py", line 47, in reraise
    raise value.with_traceback(tb)
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/opt/code/github/threefoldtech/0-templates/templates/node_capacity/node_capacity.py", line 38, in _total
    self._node_sal.capacity.register()
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/sal_zos/capacity/Capacity.py", line 111, in register
    _, resp = client.api.RegisterCapacity(data)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/api_service.py", line 167, in RegisterCapacity
    resp = self.client.post(uri, data, headers, query_params, content_type)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 62, in post
    return self._handle_data(uri, data, headers, params, content_type, self.session.post)
  File "/opt/code/github/threefoldtech/jumpscale_lib/JumpscaleLib/clients/threefold_directory/http_client.py", line 58, in _handle_data
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://capacity.threefoldtoken.com/api/nodes

2018-09-09T16:49:45.725Z: pm D > Recurring '(kvm.monitor# kvm.monitor)' in 30s
```

**Comment by chrisvdg** [comment]
Forgot to add the gist with some of the logs
https://gist.github.com/chrisvdg/08a55f4d6ce56848be1fc2d558db7a5c
